import Head from "next/head";
import EmailForm from "../views/pages/home/EmailForm/EmailForm";
import Layout from "../views/shared/Layout/Layout";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout className="landing">
                <EmailForm />
            </Layout>
        </>
    );
}
